@startuml
start
:Загрузить CSV;
:Показать стартовую комнату;
while (Игра продолжается?) is (да)
  :Прочитать команду;
  :Проверить строку;
  if (Команда известна?) then (да)
    :Выполнить команду;
  else (нет)
    :Вывести сообщение и help;
  endif
endwhile (нет)
stop
@enduml
